### ISSUE TITLE
Kullanim Hakkinda

### ISSUE THREAD

**Issue by TheZ79** [aykutalparslan/high-perfomance-tcp-server#1]
Cok ozur dileyerek soruyorum. Programlamada cok yeni oldugum icin anlamakta gucluk cektim. Soket uzerinden gelen verinin tamamlanmis halini byte[] olarak nasil elde edebilirim.

**Comment by aykutalparslan** [comment]
Tamamlanmış hali derken TCP streaming bir protokol olduğu için size sürekli bir byte stream gelir ve sizden de aynı şekilde bir stream gider. Ya uzunluğu mesajın başına ekleyerek ya da mesajın sonunda newline gibi bir karakteri arayarak mesajları birbirinden ayırt edersiniz. HTTP newline karakterini kullanır mesela. 

`var buff = result.Buffer;
byte[] arr = buff.ToArray();
`

Dediğinizde byte[] elde edersiniz ancak bu veri bir mesajın yarısı ya da tamamı olabilir.

**Comment by TheZ79** [comment]
Donus yaptiginiz icin tesekkur ederim. Ornegin asagidaki gibi mesajin tamamini alabilir miyim. Yada mesajin tamamini nasil elde ederim.


`static async Task<byte[]> ProcessConnection(Connection connection)
{
    connection.Start();
    using (var memoryStream = new MemoryStream())
    {
        while (true)
        {
            var result = await connection.Input.ReadAsync();
            var buff = result.Buffer;
            if (buff.IsSingleSegment)
            {
                await memoryStream.WriteAsync(buff.First);
            }
            else
            {
                foreach (var mem in buff)
                {
                    await memoryStream.WriteAsync(mem);
                }
            }
            connection.Input.AdvanceTo(buff.End);
            if (result.IsCompleted || result.IsCanceled)
            {
                break;
            }
        }
        connection.Shutdown();
        await connection.DisposeAsync();
        return memoryStream.ToArray();
    }
}`

**Comment by TheZ79** [comment]
Donus yaptiginiz icin tesekkur ederim. Ornegin asagidaki sekilde mesajin tamamina ulasabilir miyim. Yada ulasmam icin ne yapmaliyim.


static async Task<byte[]> ProcessConnection(Connection connection)
{
    connection.Start();
    using (var memoryStream = new MemoryStream())
    {
        while (true)
        {
            var result = await connection.Input.ReadAsync();
            var buff = result.Buffer;
            if (buff.IsSingleSegment)
            {
                await memoryStream.WriteAsync(buff.First);
            }
            else
            {
                foreach (var mem in buff)
                {
                    await memoryStream.WriteAsync(mem);
                }
            }
            connection.Input.AdvanceTo(buff.End);
            if (result.IsCompleted || result.IsCanceled)
            {
                break;
            }
        }
        connection.Shutdown();
        await connection.DisposeAsync();
        return memoryStream.ToArray();
    }
}
